name: expense
networks:
  default:
    name: expense
#   external: true
#  #if true,  docker volume create myqsl
services:
  mysql:
    image: premdaas/mysql:1.1
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    image: premdaas/backend:1.1
    container_name: backend
    command: sh -c "sleep 20 && node /app/index.js"
    depends_on:
      - mysql
  frontend:
    image: premdaas/frontend:1.1
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"