name: expense
networks:
  default:
    name: expense
volumes:
 mysql:
  external: true
 #if true,  docker volume create myqsl
services:
  mysql:
    image: premdaas/mysql:1.0
    container_name: mysql
    volumes:
     - source: mysql
       target: /var/lib/mysql
       type: volume
  backend:
    image: premdaas/backend:1.0
    container_name: backend
    depends_on:
      - mysql
  frontend:
    image: premdaas/frontend:1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"