name: expense
networks:
  default:
    name: expense
volumes:
  mysql:
              #external: true # if true, you need to create manually
                # docker volume create myqsl
          #   external: true
          #  #if true,  docker volume create myqsl
services:
  mysql:
    image: premdaas/mysql:1.1
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume # -v volume-name:/path/in/container
  backend:
    image: premdaas/backend:1.1
    container_name: backend
    command: sh -c "sleep 20 && node /app/index.js"
    depends_on:
      - mysql
  frontend:
    image: premdaas/frontend:1.1
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"